# Generated by Django 5.0.3 on 2024-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CiteScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="value"
                    ),
                ),
                (
                    "year_published",
                    models.PositiveSmallIntegerField(verbose_name="year published"),
                ),
            ],
            options={
                "verbose_name": "CiteScore",
                "verbose_name_plural": "CiteScores",
            },
        ),
        migrations.CreateModel(
            name="GovernmentalRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="value"
                    ),
                ),
                ("date_published", models.DateField(verbose_name="date published")),
            ],
            options={
                "verbose_name": "government rating",
                "verbose_name_plural": "government ratings",
            },
        ),
        migrations.CreateModel(
            name="ImpactFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_published",
                    models.PositiveSmallIntegerField(verbose_name="year published"),
                ),
                (
                    "value_2_year",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="value (2-year)"
                    ),
                ),
                (
                    "value_5_year",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="value (5-year)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Impact Factor",
                "verbose_name_plural": "Impact Factors",
            },
        ),
    ]
