# Generated by Django 5.0.3 on 2024-03-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bibliometrics", "0001_initial"),
        ("publishing_media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="citescore",
            name="journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="publishing_media.journal",
                verbose_name="journal",
            ),
        ),
        migrations.AddField(
            model_name="governmentalrating",
            name="journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="publishing_media.journal",
                verbose_name="journal",
            ),
        ),
        migrations.AddField(
            model_name="impactfactor",
            name="journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="publishing_media.journal",
                verbose_name="journal",
            ),
        ),
    ]
