# Generated by Django 5.1.2 on 2024-10-18 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("human_resources", "0001_initial"),
        ("publishers", "0001_initial"),
        ("science_classification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="title")),
                (
                    "year_published",
                    models.PositiveSmallIntegerField(verbose_name="year published"),
                ),
                (
                    "doi",
                    models.CharField(blank=True, max_length=255, verbose_name="DOI"),
                ),
                (
                    "volume",
                    models.CharField(blank=True, max_length=255, verbose_name="volume"),
                ),
                (
                    "issue",
                    models.CharField(blank=True, max_length=255, verbose_name="issue"),
                ),
                (
                    "pagination",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="pagination"
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        related_query_name="article",
                        to="publishers.journal",
                        verbose_name="journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(blank=True, max_length=255, verbose_name="alias"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authors",
                        related_query_name="author",
                        to="human_resources.contract",
                        verbose_name="contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "author",
                "verbose_name_plural": "authors",
            },
        ),
        migrations.CreateModel(
            name="ArticleContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="order")),
                (
                    "unit_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="unit ID"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        related_query_name="contribution",
                        to="research_output.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="science_classification.discipline",
                        verbose_name="discipline",
                    ),
                ),
                (
                    "unit_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="unit type",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_contributions",
                        related_query_name="article_contribution",
                        to="research_output.author",
                        verbose_name="author",
                    ),
                ),
            ],
            options={
                "verbose_name": "article contribution",
                "verbose_name_plural": "article contributions",
            },
        ),
    ]
