commit-msg:
  jobs:
    - name: commitlint
      only:
        - ref: main
      run: npx commitlint --edit {1}

pre-commit:
  jobs:
    - name: prettier
      run: npx prettier --check .
    - name: uv
      run: uv lock --check
    - name: ruff
      env:
        UV_FROZEN: "true"
      group:
        jobs:
          - name: check
            run: uv run ruff check .
          - name: format
            run: uv run ruff format --diff .

output:
  - meta
  - summary
