pre-commit:
  jobs:
    - name: prettier
      run: npx --no-install prettier --check .
    - name: uv
      run: uv lock --check
    - name: ruff
      env:
        UV_LOCKED: "true"
      group:
        jobs:
          - name: check
            run: uv run ruff check .
          - name: format
            run: uv run ruff format --diff .
    - name: django
      env:
        UV_LOCKED: "true"
      group:
        jobs:
          - name: check
            run: uv run manage.py check
          - name: makemigrations
            run: uv run manage.py makemigrations --check
          - name: makemessages
            run: |
              uv run manage.py makemessages --all --no-location --no-obsolete
              git diff --exit-code ":(glob)**/*.po"

output:
  - meta
  - summary
