pre-commit:
  jobs:
    - name: prettier
      run: npx --no-install prettier --check {staged_files}
      glob:
        - "*.json"
        - "*.md"
        - "*.yml"
    - name: uv
      run: uv lock --check
      glob:
        - ".python-version"
        - "pyproject.toml"
        - "uv.lock"
