pre-commit:
  jobs:
    - name: prettier
      run: npx --no-install prettier --check {staged_files}
      glob:
        - "*.json"
        - "*.md"
        - "*.yml"
    - name: uv
      run: uv lock --check
      glob:
        - ".python-version"
        - "pyproject.toml"
        - "uv.lock"
    - name: ruff
      env:
        UV_NO_SYNC: "true"
      group:
        jobs:
          - name: check
            run: uv run ruff check {staged_files}
          - name: format
            run: uv run ruff format --diff {staged_files}
      glob:
        - "*.py"
    - name: djlint
      env:
        UV_NO_SYNC: "true"
      group:
        jobs:
          - name: lint
            run: uv run djlint --lint --check {staged_files}
          - name: reformat
            run: uv run djlint --reformat --check {staged_files}
      glob:
        - "reactor/**/templates/**/*.html"
    - name: django
      env:
        DJANGO_SETTINGS_MODULE: "reactor.conf.settings.dev"
        UV_NO_SYNC: "true"
      group:
        jobs:
          - name: check
            run: uv run python -m django check --fail-level=ERROR
          - name: makemigrations
            run: uv run python -m django makemigrations --check
          - name: makemessages
            run: |
              uv run python -m django makemessages --all --no-location --no-obsolete
              git diff --exit-code ":(glob)**/*.po"
      glob:
        - ".python-version"
        - "pyproject.toml"
        - "reactor/**/*.py"
        - "uv.lock"
