pre-commit:
  jobs:
    - name: prettier
      run: npx --no-install prettier --check {staged_files}
      glob:
        - "*.json"
        - "*.md"
        - "*.yml"
    - name: uv
      run: uv lock --check
      glob:
        - ".python-version"
        - "pyproject.toml"
        - "uv.lock"
    - name: ruff
      env:
        UV_NO_SYNC: "true"
      group:
        jobs:
          - name: check
            run: uv run ruff check {staged_files}
          - name: format
            run: uv run ruff format --diff {staged_files}
      glob:
        - "*.py"
