default_stages:
  - pre-commit

default_install_hook_types:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --check .
        language: system
        pass_filenames: false
      - id: uv
        name: uv
        entry: uv lock --locked
        language: system
        pass_filenames: false
      - id: ruff-check
        name: ruff (check)
        entry: uv run ruff check
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff (format)
        entry: uv run ruff format
        language: system
        pass_filenames: false
      - id: django-check
        name: django (check)
        language: system
        entry: uv run manage.py check
        pass_filenames: false
      - id: django-makemigrations
        name: django (makemigrations)
        language: system
        entry: uv run manage.py makemigrations --check
        pass_filenames: false
