# Pre-commit
# https://pre-commit.com

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.0"
    hooks:
      - id: poetry-check
        args:
          - --lock
      - id: poetry-lock
        args:
          - --no-update
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        args:
          - --no-error-on-unmatched-pattern
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: "v0.13.0"
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.5.7"
    hooks:
      - id: ruff
      - id: ruff-format
        args:
          - --check
  - repo: https://github.com/djlint/djLint
    rev: "v1.34.1"
    hooks:
      - id: djlint-django
      - id: djlint-reformat-django
  - repo: local
    hooks:
      - id: django-check
        name: django-check
        entry: poetry run python manage.py check --fail-level=ERROR
        language: system
        pass_filenames: false
        types:
          - python
      - id: django-collectstatic
        name: django-collectstatic
        entry: poetry run python manage.py collectstatic --dry-run --no-input
        language: system
        pass_filenames: false
        types:
          - python
      - id: django-makemessages
        name: django-makemessages
        entry: poetry run python manage.py makemessages --all --add-location=file
        language: system
        pass_filenames: false
        types:
          - python
      - id: django-compilemessages
        name: django-compilemessages
        entry: poetry run python manage.py compilemessages
        language: system
        pass_filenames: false
        types:
          - python
      - id: django-makemigrations
        name: django-makemigrations
        entry: poetry run python manage.py makemigrations --check --dry-run --no-input
        language: system
        pass_filenames: false
        types:
          - python
      - id: django-migrate
        name: django-migrate
        entry: poetry run python manage.py migrate --no-input
        language: system
        pass_filenames: false
        types:
          - python
