; Pytest
; https://docs.pytest.org/en/latest/reference/reference.html#configuration-options

[pytest]
addopts =
  -ra
  --strict-markers
  ;
  ; pytest-django
  ; https://pytest-django.readthedocs.io/en/latest/configuring_django.html
  --ds=tests.settings
  --dc=Tests
  ;
  ; pytest-cov
  ; https://pytest-cov.readthedocs.io/en/latest/config.html#reference
  --cov
  --cov-report=term
  ;
  ; pytest-custom-exit-code
  ; https://github.com/yashtodi94/pytest-custom_exit_code#usage
  --suppress-no-test-exit-code
filterwarnings =
  ignore::DeprecationWarning
  ignore::PendingDeprecationWarning
python_files = test_*.py tests.py
pythonpath = . src
testpaths = tests
