extend-exclude = [
  "reactor/**/migrations/**/*.py",
]

[lint]
select = ["ALL"]
ignore = [
  "ANN",
  "D1",
  "PLC0415",
  "RUF012",
]

[lint.per-file-ignores]
"reactor/**/checks.py" = [
  "ARG001",
]
"reactor/conf/settings/**/*.py" = [
  "N802",
]
"tests/**/*.py" = [
  "ARG",
  "E501",
  "S101",
]

[lint.flake8-self]
extend-ignore-names = [
  "_meta",
]

[lint.isort]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "django",
  "first-party",
  "local-folder",
]

[lint.isort.sections]
django = ["django"]

[lint.pydocstyle]
convention = "google"
