[project]
name = "reactor"
version = "1.dev0"
requires-python = ">=3.14"

[dependency-groups]
dev = [
  { include-group = "pytest" },
  { include-group = "ruff" },
]
pytest = [
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
  "pytest-mock>=3.15.1",
  "pytest-randomly>=5.0.0",
]
ruff = [
  "ruff>=0.16.6",
]
