# Generated by Django 5.0.3 on 2024-03-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("publishing_media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="title")),
                ("number", models.CharField(max_length=255, verbose_name="number")),
                ("date_filed", models.DateField(verbose_name="date filed")),
                (
                    "date_published",
                    models.DateField(
                        blank=True, null=True, verbose_name="date published"
                    ),
                ),
            ],
            options={
                "verbose_name": "patent",
                "verbose_name_plural": "patents",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="title")),
                (
                    "year_published",
                    models.PositiveSmallIntegerField(verbose_name="year published"),
                ),
                (
                    "doi",
                    models.CharField(blank=True, max_length=255, verbose_name="DOI"),
                ),
                (
                    "volume_issue",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="volume/issue"
                    ),
                ),
                (
                    "pagination",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="pagination"
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishing_media.journal",
                        verbose_name="journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="title")),
                (
                    "year_published",
                    models.PositiveSmallIntegerField(verbose_name="year published"),
                ),
                (
                    "doi",
                    models.CharField(blank=True, max_length=255, verbose_name="DOI"),
                ),
                (
                    "chapter_title",
                    models.TextField(blank=True, verbose_name="chapter title"),
                ),
                (
                    "pagination",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="pagination"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=255, verbose_name="ISBN"),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishing_media.publisher",
                        verbose_name="publisher",
                    ),
                ),
            ],
            options={
                "verbose_name": "book/chapter",
                "verbose_name_plural": "books & chapters",
            },
        ),
    ]
