# Generated by Django 5.0.3 on 2024-03-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "media_types",
                    models.ManyToManyField(
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="media types",
                    ),
                ),
            ],
            options={
                "verbose_name": "publisher",
                "verbose_name_plural": "publishers",
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "abbreviation",
                    models.CharField(max_length=255, verbose_name="abbreviation"),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishing_media.publisher",
                        verbose_name="publisher",
                    ),
                ),
            ],
            options={
                "verbose_name": "journal",
                "verbose_name_plural": "journals",
            },
        ),
    ]
