name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
      - name: Install Prettier
        run: |
          npm install --no-save prettier
      - name: Run Prettier
        run: |
          npx prettier --check .
  uv:
    name: uv.lock
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Check uv.lock
        run: |
          uv lock --check
