name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm install --no-save prettier
      - run: npx prettier --check .
  uv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv lock --check
  ruff:
    needs:
      - uv
    strategy:
      matrix:
        command:
          - check
          - format
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv sync --group ruff --frozen
      - run: >-
          uv run ruff ${{ matrix.command }}
          ${{ matrix.command == 'check' && '--output-format github' || '' }}
          ${{ matrix.command == 'format' && '--diff' || '' }}
  djlint:
    needs:
      - uv
    strategy:
      matrix:
        command:
          - lint
          - reformat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv sync --group djlint --frozen
      - run: uv run djlint ${{ format('--{0}', matrix.command) }} --check .
  django:
    needs:
      - uv
    strategy:
      matrix:
        database-engine:
          - sqlite
          - postgres
      fail-fast: false
    services:
      postgres:
        image: ${{ matrix.database-engine == 'postgres' && 'postgres:latest' || '' }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv sync --extra ${{ matrix.database-engine }} --frozen
      - run: |
          uv run manage.py check
          uv run manage.py makemigrations --check
          uv run manage.py migrate --no-input
        env:
          DATABASE_ENGINE: ${{ matrix.database-engine }}
  pytest:
    needs:
      - django
    strategy:
      matrix:
        database-engine:
          - sqlite
          - postgres
      fail-fast: false
    services:
      postgres:
        image: ${{ matrix.database-engine == 'postgres' && 'postgres:latest' || '' }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv sync --group tests --extra ${{ matrix.database-engine }} --frozen
      - run: uv run pytest
        env:
          DATABASE_ENGINE: ${{ matrix.database-engine }}
