name: Django

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  django:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database-engine:
          - postgres
          - sqlite
      fail-fast: false
    env:
      DATABASE_ENGINE: ${{ matrix.database-engine }}
    services:
      postgres:
        image: ${{ matrix.database-engine == 'postgres' && 'postgres:latest' || '' }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - run: uv sync --extra ${{ matrix.database-engine }} --frozen
      - run: uv run manage.py check
      - run: uv run manage.py makemigrations --check --no-input
      - run: uv run manage.py migrate --no-input
