name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db-alias:
          - sqlite
      fail-fast: false
    env:
      DB_ALIAS: ${{ matrix.db-alias }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - run: uv sync --extra ${{ matrix.db-alias }} --group tests --frozen
      - run: uv run pytest
