name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database-engine:
          - sqlite
      fail-fast: false
    env:
      DATABASE_ENGINE: ${{ matrix.database-engine }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - run: uv sync --extra ${{ matrix.database-engine }} --group tests --frozen
      - run: uv run pytest --cov-report xml:coverage.xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.database-engine }}
          path: ./coverage.xml
          if-no-files-found: error
  codecov:
    needs:
      - pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
