name: UV

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  uv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - run: uv lock --locked
